# Generated by Django 5.1.2 on 2024-12-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceapilog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='serviceapilog',
            name='third_party',
        ),
        migrations.AddField(
            model_name='serviceapilog',
            name='ok',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
